version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hometap-backend
    ports:
      - "5001:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hometap-frontend
    ports:
      - "5002:5173"